repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./.github/config/.isort.cfg .
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config ./.github/config/.black . --extend-exclude
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config ./.github/config/.flake8 .
        language: system
        types: [ python ]
        pass_filenames: false