version: "2"

services:
  tb_project:
    image: tb_docker:latest
    container_name: tb_project
    depends_on:
      - tb_postgres
    volumes:
      - static_volume:/topblog/static
      - media_volume:/topblog/media
    ports:
      - "8002:8003"
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
      - VIRTUAL_PORT=8002
    command: >
      bash -c "python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate  && gunicorn -b 0.0.0.0:8002 topblog.wsgi:application"
  tb_daphne:
    user: root
    image: tb_docker:latest
    container_name: tb_daphne
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - redis
    links:
      - redis
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
      - VIRTUAL_PORT=8001
    command: >
      bash -c "daphne -b 0.0.0.0 -p 8001 topblog.asgi:application"
  tb_postgres:
    image: postgres:15
    container_name: tb_postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - .env
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: tb_nginx
#    image: tb_nginx
    volumes:
      - static_volume:/topblog/static
      - media_volume:/topblog/media
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - tb_project
      - tb_daphne
    links:
      - tb_daphne
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "${NGINX_EXTERNAL_SSL_PORT}:443"
  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: tb_acme_companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh

volumes:
  static_volume:
  media_volume:
  pgdbdata:
  certs:
  vhost:
  html:
  acme:
