# Generated by Django 4.1.2 on 2024-03-04 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Like of comment',
                'verbose_name_plural': 'Likes of comments',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Post ID')),
                ('image', models.ImageField(upload_to='post_images', verbose_name='Post image')),
                ('caption', models.TextField(blank=True, max_length=1000, verbose_name='Caption')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of creation')),
                ('no_of_likes', models.IntegerField(default=0, verbose_name='Number of likes')),
                ('comments_status', models.BooleanField(default=True, verbose_name='Comments(uncheck the box to turn off the comments)')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Comment text')),
                ('no_of_likes', models.IntegerField(default=0, verbose_name='Comment likes')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of creation')),
            ],
            options={
                'verbose_name': 'Post comment',
                'verbose_name_plural': 'Post comments',
            },
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Post like',
                'verbose_name_plural': 'Post likes',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=300, verbose_name='Information')),
                ('profile_img', models.ImageField(default='blank_profile.png', upload_to='profile_images', verbose_name='Profile image')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserFavoritePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': "User's favourite post",
                'verbose_name_plural': "User's favourite posts",
            },
        ),
    ]
