# Generated by Django 4.1.2 on 2022-11-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commentss_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='commentss',
            name='no_of_likes',
            field=models.IntegerField(default=0, verbose_name='Кол-во лайков'),
            preserve_default=False,
        ),
    ]
