# Generated by Django 4.1.2 on 2022-11-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_likecomment_commentss_no_of_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeComment',
            new_name='LikeComments',
        ),
    ]
