# Generated by Django 4.1.2 on 2023-08-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profile_id_user_alter_message_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersCount',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='core.profile', verbose_name='Подписки'),
        ),
    ]
