# Generated by Django 4.1.2 on 2023-08-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_followerscount_profile_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='followingf',
        ),
    ]
