# Generated by Django 4.1.2 on 2023-08-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_following_profile_followingf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followingf',
            new_name='following',
        ),
    ]
