# Generated by Django 4.1.2 on 2023-09-26 20:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_alter_post_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeComments',
            new_name='CommentLikes',
        ),
        migrations.RenameModel(
            old_name='Commentss',
            new_name='PostComments',
        ),
        migrations.RenameModel(
            old_name='LikePost',
            new_name='PostLikes',
        ),
    ]
