# Generated by Django 4.1.2 on 2023-09-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_likecomments_commentlikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disable_comments',
            field=models.BooleanField(default=False),
        ),
    ]
