# Generated by Django 4.1.2 on 2023-10-11 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_post_disable_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='username',
        ),
        migrations.AddField(
            model_name='postlikes',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postlikes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
