# Generated by Django 4.1.2 on 2023-10-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_commentlikes_username_commentlikes_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikes',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postcomments'),
        ),
    ]
