# Generated by Django 4.1.2 on 2023-10-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_commentlikes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlikes',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
