# Generated by Django 4.1.2 on 2023-11-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_post_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='no_of_likes',
            field=models.IntegerField(verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Comment'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
