# Generated by Django 4.1.2 on 2023-12-10 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_message_author_remove_message_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
