# Generated by Django 4.1.2 on 2023-12-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_postcomments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='core.profile', verbose_name='Subscriptions'),
        ),
        migrations.CreateModel(
            name='UserFavouritePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.ManyToManyField(related_name='user_favourite_posts', to='core.post', verbose_name='User favourite posts')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_posts', to='core.profile')),
            ],
        ),
    ]
