# Generated by Django 4.1.2 on 2023-12-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_userfavoriteposts_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavoriteposts',
            old_name='posts',
            new_name='post',
        ),
    ]
