# Generated by Django 4.1.2 on 2023-12-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_message_author_remove_message_chat_and_more'),
        ('chat', '0003_rename_room_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.profile'),
            preserve_default=False,
        ),
    ]
